name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependencies
        run: python -m pip install -r requirements.txt
      - name: generate html
        run: python generate_html.py data.yml
      - name: save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: output/safety.html
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: install dependencies
        run: python -m pip install -r requirements.txt
      - name: generate latex
        run: python generate_latex.py data.yml
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: output/safety.tex
          work_in_root_file_dir: true
      - name: save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: output/safety.pdf
